name = "parciales"
defaultTargets = ["Comun", "Parciales", "Ejemplos", "Guias"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.34.1"

[[lean_lib]]
name = "Comun"

[[lean_lib]]
name = "Parciales"

[[lean_lib]]
name = "Ejemplos"

[[lean_lib]]
name = "Guias"
